# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b30018e5de0ff678df28eaa33ac7bbf7452fa4093769cc52897a4c4c9c1bd28f11104bfed7e930a510ec89d649ceccb0e9eb996406231877089f9bb3eaacab

test:
  secret_key_base: f299cb98b671860a6856854297c4c93e09fe650fd193cdfaa2bf44c8e6a51c4808715725c1994620a454db83fb293419519a2b0baa39fcd5b6c73c62c51eea62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
